
name: Test

on: [push]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        version: 10.x
    - name: Install dependencies from Yarn
      run: yarn install --frozen-lockfile
    - name: Build Typescript sources
      run: yarn workspace @mavenomics/metapackage run build
    - name: Lint sources
      run: yarn run lint
    - name: Run unit tests
      run: yarn run test --silent
